Repository Build-Up-1214/Algorithm-Study, pull requests merged in 2023-02, with the labels that each got.

#37 노태윤 : 완전탐색
  NTY/BOJ/백트래킹/14888_연산자끼워넣기/연산자끼워넣기.java
  NTY/BOJ/백트래킹/9663_N-Queen/NQueen.java
  NTY/BOJ/브루트포스/1107_리모컨/리모컨.java
  NTY/BOJ/브루트포스/15683_감시/감시.java
  NTY/BOJ/브루트포스/2615_오목/오목.java
  NTY/BOJ/브루트포스/2961_도영이가만든맛있는음식(+비트마스킹)/도영이가만든맛있는음식.java
Labels: 완료

#38 장유정 : 완전탐색
  yujung/BOJ/bruteforce/1018_체스판다시칠하기.py
  yujung/BOJ/bruteforce/1436_영화감독숌.py
  yujung/BOJ/bruteforce/2309_일곱난쟁이.py
  yujung/BOJ/bruteforce/7568_덩치.py
  yujung/PRG/bruteforce/모의고사.py
  yujung/PRG/bruteforce/최소직사각형.py
Labels: 완료

#41 이가형 : 완전 탐색
  hyeongiii/BOG/bruteforce search/2309_일곱 난쟁이.py
  hyeongiii/이코테/simulation/게임개발.py
  hyeongiii/이코테/simulation/상하좌우(모범답안).py
  hyeongiii/이코테/simulation/상하좌우.py
  hyeongiii/이코테/simulation/시각(완전 탐색).py
  hyeongiii/이코테/simulation/왕실의 나이트.py
Labels: 진행 중

#39 김영현 : 완전탐색
  KYH/BOJ/BruteForce/B1062_가르침.java
  KYH/BOJ/BruteForce/B14500_테트로미노.java
  KYH/BOJ/BruteForce/B14502_연구소.java
  KYH/BOJ/BruteForce/B15684_사다리조작.java
  KYH/BOJ/BruteForce/B15686_치킨배달.java
  KYH/BOJ/BruteForce/B1759_암호만들기.java
  KYH/BOJ/BruteForce/B2798_블랙잭.java
Labels: 진행 중

#40 최수혜 : 완전탐색
  suhye/BOJ/bruteforce/1182_부분수열의합.py
  suhye/BOJ/bruteforce/1476_날짜계산.py
  suhye/BOJ/bruteforce/2210_숫자판점프.py
  suhye/BOJ/bruteforce/2309_일곱난쟁이.py
  suhye/BOJ/bruteforce/3085_사탕게임.py
  suhye/BOJ/bruteforce/7568_덩치.py
  suhye/PRG/bruteforce/전력망을둘로나누기.py
Labels: 진행 중

#44 이가형 : 그리디
  hyeongiii/이코테/greedy/1이 될 때까지.py
  hyeongiii/이코테/greedy/곱하기 혹은 더하기.py
  hyeongiii/이코테/greedy/만들 수 없는 금액.py
  hyeongiii/이코테/greedy/모험가 길드.py
  hyeongiii/이코테/greedy/문자열 뒤집기.py
  hyeongiii/이코테/greedy/볼링공 고르기.py
  hyeongiii/이코테/greedy/숫자 카드 게임.py
  hyeongiii/이코테/greedy/큰 수의 법칙(1).py
  hyeongiii/이코테/greedy/큰 수의 법칙(2).py
  hyeongiii/이코테/greedy/큰 수의 법칙.py
Labels: 진행 중

#45 김영현 : 그리디
  KYH/BOJ/Greedy/B1026_보물.java
  KYH/BOJ/Greedy/B1339_단어수학.java
  KYH/BOJ/Greedy/B1541_잃어버린괄호.java
  KYH/BOJ/Greedy/B1715_카드정렬하기.java
  KYH/BOJ/Greedy/B1931_회의실배정.java
  KYH/BOJ/Greedy/B1946_신입사원.java
Labels: 완료

#43 장유정 : 그리디
  yujung/BOJ/greedy/10162_전자레인지.py
  yujung/BOJ/greedy/1026_보물.py
  yujung/BOJ/greedy/10610_30.py
  yujung/BOJ/greedy/13305_주유소.py
  yujung/BOJ/greedy/1439_뒤집기.py
  yujung/BOJ/greedy/1789_수들의합.py
  yujung/BOJ/greedy/1931_회의실배정.py
  yujung/BOJ/greedy/1946_신입사원.py
  yujung/BOJ/greedy/2217_로프.py
  yujung/BOJ/greedy/5585_거스름돈.py
Labels: 완료

#42 노태윤 : 그리디
  NTY/BOJ/그리디/11497_통나무건너뛰기/통나무건너뛰기.java
  NTY/BOJ/그리디/11501_주식/주식.java
  NTY/BOJ/그리디/1541_잃어버린괄호/잃어버린괄호.java
  NTY/BOJ/그리디/16953_A->B/A_B.java
  NTY/BOJ/그리디/1715_카드정렬하기/카드정렬하기.java
  NTY/BOJ/그리디/1783_병든나이트/병든나이트.java
  NTY/BOJ/그리디/1946_신입사원/신입사원.java
  NTY/BOJ/그리디/2839_설탕배달/설탕배달.java
Labels: 완료

#46 최수혜 : 그리디
  suhye/BOJ/greedy/1026_보물.py
  suhye/BOJ/greedy/11047_동전0.py
  suhye/BOJ/greedy/11399_ATM.py
  suhye/BOJ/greedy/1931_회의실배정.py
  suhye/BOJ/greedy/2217_로프.py
Labels: 진행 중

#47 자율 : 노태윤
  NTY/BOJ/DP/2579_계단오르기/계단오르기.java
  NTY/BOJ/그래프/10026_적록색약/적록색약.java
  NTY/BOJ/그래프/11403_경로찾기/경로찾기.java
  NTY/BOJ/그리디/11047_동전0/동전0.java
  NTY/BOJ/누적합/11659_구간합구하기4/구간합구하기4.java
  NTY/BOJ/수학/1676_팩토리얼0의개수/팩토리얼0의개수.java
  NTY/BOJ/수학/9375_패션왕신해빈/패션왕신해빈.java
Labels: 완료

#50 자율 : 장유정
  yujung/BOJ/implementation/1009_분산처리.py
  yujung/BOJ/implementation/1475_방번호.py
  yujung/BOJ/searching/4963_섬의개수.py
Labels: 진행 중

#49 자율 : 김영현
  KYH/BOJ/BinarySearch/B1072_게임.java
  KYH/BOJ/Greedy/B1026_보물.java
  KYH/BOJ/Greedy/B1049_기타줄.java
  KYH/BOJ/implementation/B12904_A와B.java
Labels: 진행 중

#48 자율 : 최수혜
  suhye/BOJ/binarysearch/10815_숫자 카드.py
  suhye/BOJ/datastructure/10828_스택.py
  suhye/BOJ/dp/1463_1로만들기.py
  suhye/BOJ/graph/1260_DFS와 BFS.py
  suhye/BOJ/graph/1697_숨바꼭질.py
  suhye/BOJ/graph/2178_미로탐색.py
  suhye/BOJ/graph/2468_안전영역.py
  suhye/BOJ/graph/2606_바이러스.py
  suhye/BOJ/graph/2644_촌수계산.py
  suhye/BOJ/graph/2667_단지번호붙이기.py
  suhye/BOJ/graph/5140_스타트링크.py
Labels: 진행 중, 완료

#52 11주차 : 노태윤
  NTY/BOJ/DP/1912_연속합/연속합.java
  NTY/BOJ/DP/9465_스티커/스티커.java
  NTY/BOJ/그리디/16953_A_B/A_B.java
  NTY/PRG/자료구조/같은숫자는싫어/같은숫자는싫어.java
  NTY/PRG/자료구조/올바른괄호/올바른괄호.java
  NTY/PRG/자료구조/폰켓몬/폰켓몬.java
Labels: 완료

#51 11주차 : 장유정
  yujung/BOJ/implementation/10250_ACM호텔.py
  yujung/BOJ/math/1929_소수구하기.py
  yujung/BOJ/math/2581_소수.py
  yujung/BOJ/prefixsum/11659_구간합구하기4.py
  yujung/BOJ/searching/14502_연구소.py
Labels: 완료
